name: Telegram userbot

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name "rahulkhatri137"
           git config --global user.email "${{ secrets.GHMAIL }}"         
           sudo -E apt-get clean 
           sudo apt install expect -y

       - name: cloning repo
         run: |
           expect -c " 
           spawn git clone https://github.com/rahulkhatri137/friday ubot
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -5
           catch wait result
           interact"
       - name: Running Bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd ubot
           echo "${{ secrets.DPASS }}" | docker login -u rahulkhatri137 --password-stdin
           docker container prune --force || true
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t ubot
           docker image ls
           docker run --privileged --rm -i ubot
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/rahulkhatri137/ub-wf loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
