#Docker Work na BSDK

name: setting up environment

on: [push]
    
env:
 username: rahulkhatri137
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           docker rmi `docker images -q`
           git config --global user.name "rahulkhatri137"
           git config --global user.email "rahulkhatri137@gmail.com"         
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get clean 
           sudo apt install expect -y

       - name: cloning repo
         continue-on-error: true
         run: |
           expect -c " 
           spawn git clone ${{ secrets.CREDS }} ultroid
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -5
           catch wait result
           interact"
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd ultroid
           docker-compose up -d
           docker-compose logs -f
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/rahulkhatri137/ult-ub-wf loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
